version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - /fly-feel/sql/:/docker-entrypoint-initdb.d/
      #- /devops-manager/mysql/conf/my.cnf:/etc/my.cnf
      - /mnt/sda1/var/lib/mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fly-feel
      MYSQL_PASS: fly-feel2022!
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --port 6379 --requirepass root  --appendonly yes
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /mnt/sda1/var/lib/mongo/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  rabbitmq:
    image: rabbitmq:3.8.3-management
    restart: always
    ports:
      - '15672:15672'   # web UI 管理接口
      - '5672:5672'    # 生产者和消费者连接使用的接口
    volumes:
      - /mnt/sda1/var/lib/rabbit/log:/var/log/rabbitmq #挂载 RabbitMQ日志
      - /mnt/sda1/var/lib/rabbit/data:/var/lib/rabbitmq #挂载 RabbitMQ数据
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
  minio:
    image: minio/minio
    ports:
      - '9000:9000' # api 端口
      - '9001:9001' # 控制台端口
    environment:
      MINIO_ACCESS_KEY: root    #管理后台用户名
      MINIO_SECRET_KEY: rootroot #管理后台密码，最小8个字符
    volumes:
      - /mnt/sda1/var/lib/minio/data:/data               #映射当前目录下的data目录至容器内/data目录
      - /mnt/sda1/var/lib/minio/config:/root/.minio/     #映射配置目录
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always